name: jobpilot
description: A Job finding app made by TemplateCookie.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  readmore: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/identity/
