name: jobpilot
description: A Job finding app made by TemplateCookie.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  get: ^4.6.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/identity/
