import 'package:flutter/material.dart';

const EdgeInsets all0 = EdgeInsets.zero;

const EdgeInsets horizontal3 = EdgeInsets.symmetric(horizontal: 3);
const EdgeInsets vertical3 = EdgeInsets.symmetric(vertical: 3);
const EdgeInsets all3 = EdgeInsets.all(3);
const EdgeInsets horizontal4 = EdgeInsets.symmetric(horizontal: 4);
const EdgeInsets vertical4 = EdgeInsets.symmetric(vertical: 4);
const EdgeInsets all4 = EdgeInsets.all(4);
const EdgeInsets horizontal6 = EdgeInsets.symmetric(horizontal: 6);
const EdgeInsets vertical6 = EdgeInsets.symmetric(vertical: 6);
const EdgeInsets all6 = EdgeInsets.all(6);
const EdgeInsets horizontal8 = EdgeInsets.symmetric(horizontal: 8);
const EdgeInsets vertical8 = EdgeInsets.symmetric(vertical: 8);
const EdgeInsets all8 = EdgeInsets.all(8);
const EdgeInsets horizontal10 = EdgeInsets.symmetric(horizontal: 10);
const EdgeInsets vertical10 = EdgeInsets.symmetric(vertical: 10);
const EdgeInsets all10 = EdgeInsets.all(10);
const EdgeInsets horizontal12 = EdgeInsets.symmetric(horizontal: 12);
const EdgeInsets vertical12 = EdgeInsets.symmetric(vertical: 12);
const EdgeInsets all12 = EdgeInsets.all(12);
const EdgeInsets horizontal16 = EdgeInsets.symmetric(horizontal: 16);
const EdgeInsets vertical16 = EdgeInsets.symmetric(vertical: 16);
const EdgeInsets all16 = EdgeInsets.all(16);
const EdgeInsets horizontal18 = EdgeInsets.symmetric(horizontal: 18);
const EdgeInsets vertical18 = EdgeInsets.symmetric(vertical: 18);
const EdgeInsets all18 = EdgeInsets.all(18);
const EdgeInsets horizontal20 = EdgeInsets.symmetric(horizontal: 20);
const EdgeInsets vertical20 = EdgeInsets.symmetric(vertical: 20);
const EdgeInsets all20 = EdgeInsets.all(20);
